/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uts_pbo;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Cika Andini
 */
public class Frame_Login extends javax.swing.JFrame {

    /**
     * Creates new form Frame_Login
     */
    public Frame_Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUSERNAME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSIGNUP = new javax.swing.JButton();
        btnEXIT = new javax.swing.JButton();
        btnLOGIN = new javax.swing.JButton();
        txtPASSWORD = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\JAVA NETBEANS\\IMG-20161118-WA0005.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(110, 10, 240, 220);

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel2.setText("USERNAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(180, 230, 110, 30);
        jPanel1.add(txtUSERNAME);
        txtUSERNAME.setBounds(110, 260, 240, 40);

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel3.setText("PASSWORD");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(180, 310, 110, 30);

        btnSIGNUP.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnSIGNUP.setText("SIGNUP");
        btnSIGNUP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSIGNUPActionPerformed(evt);
            }
        });
        jPanel1.add(btnSIGNUP);
        btnSIGNUP.setBounds(30, 400, 100, 40);

        btnEXIT.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnEXIT.setText("EXIT");
        btnEXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEXITActionPerformed(evt);
            }
        });
        jPanel1.add(btnEXIT);
        btnEXIT.setBounds(190, 400, 90, 40);

        btnLOGIN.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        btnLOGIN.setText("LOGIN");
        btnLOGIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLOGINActionPerformed(evt);
            }
        });
        jPanel1.add(btnLOGIN);
        btnLOGIN.setBounds(340, 400, 100, 40);
        jPanel1.add(txtPASSWORD);
        txtPASSWORD.setBounds(110, 340, 240, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 550, 510);

        setBounds(0, 0, 500, 507);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSIGNUPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSIGNUPActionPerformed
        String username = txtUSERNAME.getText();
        String password = txtPASSWORD.getText();
        if ("".equals(txtUSERNAME.getText()) || "".equals(txtPASSWORD.getText())) {
            JOptionPane.showMessageDialog(this, "Isikan Username dan Password Dahulu!!", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
        try {
            try (Statement statement = (Statement) file_koneksi.GetConnection().createStatement()) {
                statement.executeUpdate("INSERT INTO `tb_user`(username, password) VALUES ('"+username+"', '"+password+"')");
            }
            JOptionPane.showMessageDialog(null, "Selamat! Anda Berhasil Sign Up!");
        } catch (Exception t) {
            JOptionPane.showMessageDialog(null, "Mohon maaf, ulangi lagi prosedur");
        }
        }
    }//GEN-LAST:event_btnSIGNUPActionPerformed

    private void btnEXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEXITActionPerformed
        dispose();
    }//GEN-LAST:event_btnEXITActionPerformed

    private void btnLOGINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLOGINActionPerformed
        Connection connection;
        PreparedStatement ps;
        if ("".equals(txtUSERNAME.getText()) || "".equals(txtPASSWORD.getText())) {
            JOptionPane.showMessageDialog(this, "Isikan Username dan Password Dahulu!!", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
        try {
            connection = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/db_perpustakaan?zeroDateTimeBehavior=convertToNull", "root", "");
            ps = connection.prepareStatement("SELECT * FROM tb_user WHERE username = ? AND password = ?");
            ps.setString(1, txtUSERNAME.getText());
            ps.setString(2, txtPASSWORD.getText());
            ResultSet result = ps.executeQuery();
            if (result.next()) {
                new Main_Frame().show();
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(rootPane, "Salah!");
                txtPASSWORD.setText("");
                txtUSERNAME.requestFocus();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "gagal");
        }
      }
    }//GEN-LAST:event_btnLOGINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame_Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame_Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEXIT;
    private javax.swing.JButton btnLOGIN;
    private javax.swing.JButton btnSIGNUP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtPASSWORD;
    private javax.swing.JTextField txtUSERNAME;
    // End of variables declaration//GEN-END:variables
}
